# Generated by Django 5.0.1 on 2026-03-20 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='cliente_nome',
            field=models.CharField(blank=True, help_text='Preencha se não selecionar um cliente cadastrado', max_length=200, verbose_name='Nome do Cliente'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='oficina.cliente', verbose_name='Cliente'),
        ),
    ]
